name: Code Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.PYVER }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - PYVER: current_arch
            SKIP_SHELLCHECK: 0
            SKIP_MYPY: 0
            SKIP_VULTURE: 0

          - PYVER: python310_ubuntu_2204
            SKIP_SHELLCHECK: 1
            SKIP_MYPY: 1
            SKIP_VULTURE: 1
    env:
      PYVER: ${{ matrix.PYVER }}
      SKIP_SHELLCHECK: ${{ matrix.SKIP_SHELLCHECK }}
      SKIP_MYPY: ${{ matrix.SKIP_MYPY }}
      SKIP_VULTURE: ${{ matrix.SKIP_VULTURE }}

    steps:
    - uses: actions/checkout@v2

    - name: get Themix GUI
      run: git clone https://github.com/themix-project/oomox.git ./themix_gui/

    - name: Set env
      run: echo "THEMIX_GUI_PATH=./themix_gui/" >> $GITHUB_ENV

    - name: move dockerfiles into build context
      run: mv ./themix_gui/dockerfiles/* ./

    - name: switch base docker image
      run: sed -i -e 's|FROM archlinux:base-devel|FROM actionless/pikaur|' Dockerfile_${PYVER}

    - name: build docker image
      run: docker build . -f Dockerfile_${PYVER} -t oomox

    - name: run ci in docker
      run: docker run
        -e SKIP_SHELLCHECK=${SKIP_SHELLCHECK}
        -e SKIP_MYPY=${SKIP_MYPY}
        -e SKIP_VULTURE=${SKIP_VULTURE}
        -e THEMIX_GUI_PATH=${THEMIX_GUI_PATH}
        oomox:latest
        ./maintenance_scripts/lint.sh

    - name: run makefile ci in docker
      run: docker run
        oomox:latest
        ${THEMIX_GUI_PATH}/maintenance_scripts/makefile_shellcheck.py
        ./Makefile_oomox_plugin
